<html>
<head><style TYPE="text/css"><!--
A { text-decoration: none; }
A:hover { text-decoration: underline; }
H1 { font-family: arial,helvetica,sans-serif; font-size: 18pt; font-weight: bold;}
H2 { font-family: arial,helvetica,sans-serif; font-size: 14pt; font-weight: bold;}
BODY,TD { font-family: arial,helvetica,sans-serif; font-size: 10pt; }
TH { font-family: arial,helvetica,sans-serif; font-size: 11pt; font-weight: bold; }
//--></STYLE>
<title><?php echo "$sys_name - $sys_title" ?></title>
</head>

<body bgcolor="white" text="black">
<h1><?php echo "$sys_name - Installation and configuration check" ?></h1>
